#! /usr/bin/env node

const github = require('octonode')
const spawn = require('cross-spawn')
const normalizeUrl = require('normalize-url')
const urlRegex = require('url-regex')

if (!process.env.CI || !process.env.TRAVIS) {
  throw new Error('Could not detect Travis CI environment')
}

const githubToken = process.env.GH_TOKEN
const nowToken = process.env.NOW_TOKEN

if (!githubToken) {
  throw new Error('Missing required environment variable GH_TOKEN')
}

if (!nowToken) {
  throw new Error('Missing required environment variable NOW_TOKEN')
}

const client = github.client(githubToken)
const ghRepo = client.repo(process.env.TRAVIS_REPO_SLUG)

function deploy(context, sha) {
  let alias
  let stdout = ''
  updateStatus({
    state: 'pending',
    description: `▲ Now ${context} deployment pending`,
  })
  const isProd = context === 'production'
  let command = `now --token ${nowToken} --no-clipboard -e BUILD_INFO=$(node other/get-build-info.js)`
  if (context === 'production') {
    alias = process.env.NOW_ALIAS
    command = `now alias set $(${command}) "${alias}" --token ${nowToken}`
  }

  safeLog('spawning shell with command:', command)
  const child = spawn('sh', ['-c', command])

  if (!isProd) {
    child.stdout.on('data', data => (stdout += data))
  }

  child.stdout.on('data', data => safeLog(String(data)))
  child.stderr.on('data', data => safeError(String(data)))
  child.on('error', err => {
    safeError(err)
    updateStatus({
      state: 'error',
      description: `▲ Now ${context} deployment failed. See Travis logs for details.`,
    })
  })

  child.on('close', () => {
    const target_url = alias || getUrl(stdout)
    updateStatus({
      state: 'success',
      target_url,
      description: `▲ Now ${context} deployment complete`,
    })
  })

  function updateStatus(options) {
    const mergedOptions = Object.assign({context, target_url: alias}, options)
    console.log(`${mergedOptions.description}: ${mergedOptions.target_url}`)
    ghRepo.status(sha, mergedOptions, logError('setting complete status'))
  }
}

const {TRAVIS_EVENT_TYPE, TRAVIS_PULL_REQUEST_SHA, TRAVIS_COMMIT} = process.env

switch (TRAVIS_EVENT_TYPE) {
  case 'pull_request': {
    deploy('staging', TRAVIS_PULL_REQUEST_SHA)
    break
  }
  case 'push': {
    deploy('production', TRAVIS_COMMIT)
    break
  }
  default: {
    console.log(`${TRAVIS_EVENT_TYPE} is not supported by now-travis`)
  }
}

function getUrl(content) {
  const urls = content.match(urlRegex()) || []

  return urls.map(url => normalizeUrl(url.trim().replace(/\.+$/, '')))[0]
}

function logError(message) {
  return function onError(error) {
    if (error) {
      console.log(message, error)
    }
  }
}

function safeLog(...args) {
  const safeArgs = args.map(s => safeify(s))
  console.log(...safeArgs)
}

function safeError(...args) {
  const safeArgs = args.map(s => safeify(s))
  console.error(...safeArgs)
}

function safeify(s, safed = []) {
  if (safed.indexOf(s) !== -1) {
    return 'CIRCULAR'
  }
  safed.push(s)
  if (typeof s === 'string') {
    return s
      .split(nowToken)
      .join('NOW_TOKEN')
      .split(githubToken)
      .join('GITHUB_TOKEN')
  } else if (typeof s === 'object' && s !== null) {
    return Object.keys(s).reduce((acc, k) => {
      acc[k] = safeify(s, safed)
      return acc
    }, {})
  } else {
    return s
  }
}

// This is not transpiled
/*
  eslint
  no-console: 0,
  camelcase: 0,
  comma-dangle: [
    2,
    {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      functions: 'never'
    }
  ]
 */
