// flow-typed signature: 7f4b117f36016bf358bb11389276802d
// flow-typed version: <<STUB>>/eslint-config-kentcdodds_v^12.4.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-kentcdodds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-kentcdodds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-kentcdodds/babel-module' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/babel-react-require' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/es6/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/es6/index' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/es6/non-rules-config' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/es6/possible-errors' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/es6/stylistic' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/import/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/import/index' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/import/non-rules-config' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/import/possible-errors' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/import/stylistic' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/jest' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/jsx-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/possible-errors' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/prettier' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/react' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/stylistic' {
  declare module.exports: any;
}

declare module 'eslint-config-kentcdodds/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-kentcdodds/babel-module.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/babel-module'>;
}
declare module 'eslint-config-kentcdodds/babel-react-require.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/babel-react-require'>;
}
declare module 'eslint-config-kentcdodds/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/best-practices'>;
}
declare module 'eslint-config-kentcdodds/es6/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/es6/best-practices'>;
}
declare module 'eslint-config-kentcdodds/es6/index.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/es6/index'>;
}
declare module 'eslint-config-kentcdodds/es6/non-rules-config.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/es6/non-rules-config'>;
}
declare module 'eslint-config-kentcdodds/es6/possible-errors.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/es6/possible-errors'>;
}
declare module 'eslint-config-kentcdodds/es6/stylistic.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/es6/stylistic'>;
}
declare module 'eslint-config-kentcdodds/import/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/import/best-practices'>;
}
declare module 'eslint-config-kentcdodds/import/index.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/import/index'>;
}
declare module 'eslint-config-kentcdodds/import/non-rules-config.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/import/non-rules-config'>;
}
declare module 'eslint-config-kentcdodds/import/possible-errors.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/import/possible-errors'>;
}
declare module 'eslint-config-kentcdodds/import/stylistic.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/import/stylistic'>;
}
declare module 'eslint-config-kentcdodds/index' {
  declare module.exports: $Exports<'eslint-config-kentcdodds'>;
}
declare module 'eslint-config-kentcdodds/index.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds'>;
}
declare module 'eslint-config-kentcdodds/jest.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/jest'>;
}
declare module 'eslint-config-kentcdodds/jsx-a11y.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/jsx-a11y'>;
}
declare module 'eslint-config-kentcdodds/possible-errors.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/possible-errors'>;
}
declare module 'eslint-config-kentcdodds/prettier.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/prettier'>;
}
declare module 'eslint-config-kentcdodds/react.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/react'>;
}
declare module 'eslint-config-kentcdodds/stylistic.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/stylistic'>;
}
declare module 'eslint-config-kentcdodds/webpack.js' {
  declare module.exports: $Exports<'eslint-config-kentcdodds/webpack'>;
}
