// flow-typed signature: fa79999d48ffc4c031065f2164c91335
// flow-typed version: <<STUB>>/markdown-loader_v^2.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-loader/example/index' {
  declare module.exports: any;
}

declare module 'markdown-loader/example/webpack.config' {
  declare module.exports: any;
}

declare module 'markdown-loader/test/assets/index' {
  declare module.exports: any;
}

declare module 'markdown-loader/test/index.test' {
  declare module.exports: any;
}

declare module 'markdown-loader/test/markdown-options' {
  declare module.exports: any;
}

declare module 'markdown-loader/test/markdown-renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-loader/example/index.js' {
  declare module.exports: $Exports<'markdown-loader/example/index'>;
}
declare module 'markdown-loader/example/webpack.config.js' {
  declare module.exports: $Exports<'markdown-loader/example/webpack.config'>;
}
declare module 'markdown-loader/index' {
  declare module.exports: $Exports<'markdown-loader'>;
}
declare module 'markdown-loader/index.js' {
  declare module.exports: $Exports<'markdown-loader'>;
}
declare module 'markdown-loader/test/assets/index.js' {
  declare module.exports: $Exports<'markdown-loader/test/assets/index'>;
}
declare module 'markdown-loader/test/index.test.js' {
  declare module.exports: $Exports<'markdown-loader/test/index.test'>;
}
declare module 'markdown-loader/test/markdown-options.js' {
  declare module.exports: $Exports<'markdown-loader/test/markdown-options'>;
}
declare module 'markdown-loader/test/markdown-renderer.js' {
  declare module.exports: $Exports<'markdown-loader/test/markdown-renderer'>;
}
