// flow-typed signature: 840b3e86db204f9093769dacc6f37103
// flow-typed version: <<STUB>>/normalize-url_v^1.9.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'normalize-url/index' {
  declare module.exports: $Exports<'normalize-url'>;
}
declare module 'normalize-url/index.js' {
  declare module.exports: $Exports<'normalize-url'>;
}
