// flow-typed signature: aac14c6f59c3ab62ad5a67e2fccd95d5
// flow-typed version: <<STUB>>/octonode_v^0.7.13/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'octonode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'octonode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'octonode/lib/octonode' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/auth' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/client' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/gist' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/issue' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/label' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/me' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/milestone' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/notification' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/org' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/pr' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/project' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/release' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/repo' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/search' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/team' {
  declare module.exports: any;
}

declare module 'octonode/lib/octonode/user' {
  declare module.exports: any;
}

// Filename aliases
declare module 'octonode/lib/octonode.js' {
  declare module.exports: $Exports<'octonode/lib/octonode'>;
}
declare module 'octonode/lib/octonode/auth.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/auth'>;
}
declare module 'octonode/lib/octonode/client.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/client'>;
}
declare module 'octonode/lib/octonode/gist.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/gist'>;
}
declare module 'octonode/lib/octonode/issue.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/issue'>;
}
declare module 'octonode/lib/octonode/label.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/label'>;
}
declare module 'octonode/lib/octonode/me.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/me'>;
}
declare module 'octonode/lib/octonode/milestone.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/milestone'>;
}
declare module 'octonode/lib/octonode/notification.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/notification'>;
}
declare module 'octonode/lib/octonode/org.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/org'>;
}
declare module 'octonode/lib/octonode/pr.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/pr'>;
}
declare module 'octonode/lib/octonode/project.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/project'>;
}
declare module 'octonode/lib/octonode/release.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/release'>;
}
declare module 'octonode/lib/octonode/repo.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/repo'>;
}
declare module 'octonode/lib/octonode/search.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/search'>;
}
declare module 'octonode/lib/octonode/team.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/team'>;
}
declare module 'octonode/lib/octonode/user.js' {
  declare module.exports: $Exports<'octonode/lib/octonode/user'>;
}
