// flow-typed signature: f969169872f5260bc3182908a563d5f2
// flow-typed version: <<STUB>>/remark-html_v^6.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-html/index' {
  declare module.exports: $Exports<'remark-html'>;
}
declare module 'remark-html/index.js' {
  declare module.exports: $Exports<'remark-html'>;
}
